<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = array(
            array('productName' => 'Apple', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '2', 'category_id' => '2', 'productCode' => '0001', 'productPicture' => 'uploads/25/08/1756205484-563.png', 'product_type' => 'single', 'productDealerPrice' => '210', 'productPurchasePrice' => '200', 'productSalePrice' => '250', 'productWholeSalePrice' => '220', 'productStock' => '200', 'expire_date' => '2025-07-31', 'alert_qty' => '10.00', 'profit_percent' => '10', 'vat_amount' => '5.00', 'vat_type' => 'exclusive', 'size' => '34', 'type' => NULL, 'color' => NULL, 'weight' => '125', 'capacity' => '42', 'productManufacturer' => 'Apple', 'meta' => NULL, 'created_at' => '2025-08-18 09:20:10', 'updated_at' => '2025-08-26 16:51:24', 'vat_id' => '2', 'model_id' => NULL),
            array('productName' => 'Cabbage', 'business_id' => '1', 'unit_id' => '2', 'brand_id' => '3', 'category_id' => '3', 'productCode' => '0002', 'productPicture' => 'uploads/25/08/1756205505-67.png', 'product_type' => 'single', 'productDealerPrice' => '540', 'productPurchasePrice' => '500', 'productSalePrice' => '600', 'productWholeSalePrice' => '550', 'productStock' => '50', 'expire_date' => '2025-07-08', 'alert_qty' => '20.00', 'profit_percent' => '16', 'vat_amount' => '10.50', 'vat_type' => 'inclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Cocola', 'meta' => NULL, 'created_at' => '2025-08-18 09:20:10', 'updated_at' => '2025-08-26 16:51:45', 'vat_id' => '1', 'model_id' => NULL),
            array('productName' => 'Banana', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '4', 'category_id' => '2', 'productCode' => '0003', 'productPicture' => 'uploads/25/08/1756205519-809.png', 'product_type' => 'single', 'productDealerPrice' => '900', 'productPurchasePrice' => '800', 'productSalePrice' => '1000', 'productWholeSalePrice' => '950', 'productStock' => '100', 'expire_date' => '2025-07-08', 'alert_qty' => '5.00', 'profit_percent' => '8', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Hold', 'meta' => NULL, 'created_at' => '2025-08-18 09:20:10', 'updated_at' => '2025-08-26 16:51:59', 'vat_id' => NULL, 'model_id' => NULL),
            array('productName' => 'Beef Meat', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '1', 'category_id' => '4', 'productCode' => '0004', 'productPicture' => 'uploads/25/08/1756205549-255.png', 'product_type' => 'single', 'productDealerPrice' => '260', 'productPurchasePrice' => '250', 'productSalePrice' => '280', 'productWholeSalePrice' => '270', 'productStock' => '78', 'expire_date' => '2025-07-08', 'alert_qty' => '15.00', 'profit_percent' => '32', 'vat_amount' => '0.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Hold', 'meta' => NULL, 'created_at' => '2025-08-18 09:20:10', 'updated_at' => '2025-08-26 16:52:29', 'vat_id' => NULL, 'model_id' => NULL),
            array('productName' => 'Basmoti Rice', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '1', 'category_id' => '1', 'productCode' => '0005', 'productPicture' => 'uploads/25/08/1756205463-17.png', 'product_type' => 'single', 'productDealerPrice' => '0', 'productPurchasePrice' => '0', 'productSalePrice' => '0', 'productWholeSalePrice' => '0', 'productStock' => '1390', 'expire_date' => NULL, 'alert_qty' => '10.00', 'profit_percent' => '0', 'vat_amount' => '35.00', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Rahim Kadir', 'meta' => NULL, 'created_at' => '2025-08-21 08:57:47', 'updated_at' => '2025-08-26 16:51:03', 'vat_id' => '3', 'model_id' => NULL),
            array('productName' => 'Orange', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '2', 'category_id' => '2', 'productCode' => '0006', 'productPicture' => 'uploads/25/08/1756205444-920.png', 'product_type' => 'single', 'productDealerPrice' => '0', 'productPurchasePrice' => '0', 'productSalePrice' => '0', 'productWholeSalePrice' => '0', 'productStock' => '2323', 'expire_date' => NULL, 'alert_qty' => '10.00', 'profit_percent' => '0', 'vat_amount' => '15.99', 'vat_type' => 'inclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Milon Mollah', 'meta' => NULL, 'created_at' => '2025-08-21 09:00:34', 'updated_at' => '2025-08-26 16:50:44', 'vat_id' => '2', 'model_id' => NULL),
            array('productName' => 'Potato', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '2', 'category_id' => '3', 'productCode' => '0007', 'productPicture' => 'uploads/25/08/1756205428-336.png', 'product_type' => 'single', 'productDealerPrice' => '0', 'productPurchasePrice' => '0', 'productSalePrice' => '0', 'productWholeSalePrice' => '0', 'productStock' => '131', 'expire_date' => NULL, 'alert_qty' => '8.00', 'profit_percent' => '0', 'vat_amount' => '12.07', 'vat_type' => 'inclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Sohag Seikh', 'meta' => NULL, 'created_at' => '2025-08-21 09:04:20', 'updated_at' => '2025-08-26 16:50:28', 'vat_id' => '1', 'model_id' => NULL),
            array('productName' => 'Coriander Leaves', 'business_id' => '1', 'unit_id' => '3', 'brand_id' => '4', 'category_id' => '3', 'productCode' => '0008', 'productPicture' => 'uploads/25/08/1756205397-132.png', 'product_type' => 'single', 'productDealerPrice' => '0', 'productPurchasePrice' => '0', 'productSalePrice' => '0', 'productWholeSalePrice' => '0', 'productStock' => '1311', 'expire_date' => NULL, 'alert_qty' => '20.00', 'profit_percent' => '0', 'vat_amount' => '7.80', 'vat_type' => 'exclusive', 'size' => NULL, 'type' => NULL, 'color' => NULL, 'weight' => NULL, 'capacity' => NULL, 'productManufacturer' => 'Rana Rahman', 'meta' => NULL, 'created_at' => '2025-08-21 09:09:04', 'updated_at' => '2025-08-26 16:49:57', 'vat_id' => '2', 'model_id' => NULL)
        );

        Product::insert($products);
    }
}
